env:
  global:
    - SCP_USER=ci
    - PROD_HOST=mosey.systems
    - PROD_PATH=/var/www/undefined/html
sudo: false
language: node_js
cache:
  directories:
    - '~/.npm'
    - '~/.cache'
notifications:
  email: false
node_js:
  - '10.8'
install: npm i
jobs:
  include:
    - stage: build and deploy
      script:
        - npm run build
        - scp -i ci/travis_ci_rsa build/*.* ${SCP_USER}@${PROD_HOST}:${PROD_PATH}
branches:
  only: master
before_install:
  - openssl aes-256-cbc -K $encrypted_1364afca9c50_key -iv $encrypted_1364afca9c50_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
