env:
  global:
    - SCP_USER=ci
    - PROD_HOST=107.172.210.106
    - PROD_PATH=/var/www/undefined/build
sudo: false
language: node_js
cache:
  directories:
    - '~/.npm'
    - '~/.cache'
notifications:
  email: false
node_js:
  - '10.8'
install: npm i
jobs:
  include:
    - stage: unit tests
      script: npx jest
    - stage: automation tests
      script:
        # print all Travis environment variables for debugging
        # - $(npm bin)/print-env TRAVIS
        - npm start -- --silent &
        - npx cypress run
        # after all tests finish running we need
        # to kill all background jobs (like "npm start &")
        - kill $(jobs -p) || true
    - stage: build and deploy
      script:
        - npm run build
        - echo copying to ${SCP_USER}@${PROD_HOST}:${PROD_PATH}
        - scp -i ci/travis_ci_rsa -o "StrictHostKeyChecking=no" build/*.* ${SCP_USER}@${PROD_HOST}:${PROD_PATH}
branches:
  only: master
before_install:
  - openssl aes-256-cbc -K $encrypted_1364afca9c50_key -iv $encrypted_1364afca9c50_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
